- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: installed

- name: enable and start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: include from common role
  include_role:
    name: common

- name: copy expense config
  ansible.builtin.template: #it will be search in template folder
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx

